#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Borderlands 3 Data Processing Scripts
# Copyright (C) 2022 CJ Kucera
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the development team nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CJ KUCERA BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import sys
import json
import html
import argparse
import textwrap
import subprocess

# Default external commands we call
cmd_serialize = 'john-wick-parse.exe'


def main():

    global cmd_serialize

    # Arguments
    parser = argparse.ArgumentParser(
        description='Get dialogue lines given a dialogscript and guid',
    )

    parser.add_argument(
        '-s',
        '--serialize',
        type=str,
        default=cmd_serialize,
        help='Command to use for object serialization',
    )

    parser.add_argument(
        'filename',
        nargs=1,
        type=str,
        help='DialogScript filename',
    )

    parser.add_argument(
        '-guids',
        nargs='+',
        type=str,
        help='GUID',
    )

    args = parser.parse_args()
    cmd_serialize = args.serialize
    filename = args.filename[0]

    # Grab the filename to process
    if filename.endswith('.'):
        filename = filename[:-1]
    if '.' in filename:
        filename_base, ext = filename.rsplit('.', 1)
        if ext not in {'json', 'uasset', 'uexp'}:
            raise RuntimeError('Unknown filename: {}'.format(filename))
        filename = filename_base

    # Serialize it (might be already serialized, but don't bother checking)
    subprocess.run([cmd_serialize, 'serialize', filename])

    # Make sure it worked
    json_path = '{}.json'.format(filename)
    if not os.path.exists(json_path):
        raise RuntimeError('Could not find {}'.format(json_path))

    # Collect GUIDs into a set
    # guid_set = set(args.guids)

    DNTNames = {
        'DialogEnumValue_Character_ABRIGGA': ['Abrigga'],
        'DialogEnumValue_Character_ACE': ['Ace Baron'],
        'DialogEnumValue_Character_ADI': ['Adi'],
        'DialogEnumValue_Character_ALKONOST': ['Alkonost'],
        'DialogEnumValue_Character_ALL_IN_ALLAN': ['All-In Allan'],
        'DialogEnumValue_Character_ANGEL': ['Angel'],
        'DialogEnumValue_Character_ARCHER_ROWE': ['Archer Rowe'],
        'DialogEnumValue_Character_ARCHIMEDES': ['Archimedes'],
        'DialogEnumValue_Character_ASSASSIN_1': ['Barnabus'],
        'DialogEnumValue_Character_ATLAS_CHATTER': ['Atlas Soldier Chatter'],
        'DialogEnumValue_Character_ATLAS_SOLDIER_1': ['Atlas Soldier', 'Liam'],
        'DialogEnumValue_Character_ATLAS_SOLDIER_BAR_PATRON': ['Atlas Bar Patron'],
        'DialogEnumValue_Character_ATOMIC': ['Atomic'],
        'DialogEnumValue_Character_AURELIA': ['Aurelia'],
        'DialogEnumValue_Character_AVA': ['Ava'],
        'DialogEnumValue_Character_AXTON': ['Axton'],
        'DialogEnumValue_Character_AZALEA': ['Azalea'],
        'DialogEnumValue_Character_BABY': ['Baby'],
        'DialogEnumValue_Character_BALDRIN': ['Baldrin'],
        'DialogEnumValue_Character_BALEX': ['BALEX'],
        'DialogEnumValue_Character_BANDIT': ['Psycho'],
        'DialogEnumValue_Character_BANDIT_1': ['Bandit'],
        'DialogEnumValue_Character_BANDIT_2': ['Bandit'],
        'DialogEnumValue_Character_BANDIT_3': ['Bandit'],
        'DialogEnumValue_Character_BANDIT_BATTLE_WAVE': ['Bandits'],
        'DialogEnumValue_Character_BANDIT_BIRTHDAY_WALLA': ['Bandits'],
        'DialogEnumValue_Character_BANDIT_FEMALE_1': ['Grabby Gretchen'],
        'DialogEnumValue_Character_BANDIT_MALE_1': ['Looter', 'Handsome Slacks', 'Hungry Henry', 'Moist Hand Luke'],
        'DialogEnumValue_Character_BANDIT_MALE_2': ['Looter', 'Cowardly Colin', 'Handsome Jacket'],
        'DialogEnumValue_Character_BANDIT_WALLA': ['Bandits'],
        'DialogEnumValue_Character_BANSHEE': ['Banshee'],
        'DialogEnumValue_Character_BARISTA_BOT': ['Barista Bot'],
        'DialogEnumValue_Character_BARKEEP': ['Barkeep'],
        'DialogEnumValue_Character_BARON_NOGGIN': ['Baron Noggin'],
        'DialogEnumValue_Character_BAR_PATRON': ['Bar Patron'],
        'DialogEnumValue_Character_BEANS': ['Private Beans'],
        'DialogEnumValue_Character_BEATRICE': ['Beatrice'],
        'DialogEnumValue_Character_BEAU': ['Beau'],
        'DialogEnumValue_Character_BEEF_PLISSKEN': ['Beef Plissken'],
        'DialogEnumValue_Character_BENEDICT': ['Dr. Benedict'],
        'DialogEnumValue_Character_BERGAN': ['Bergan'],
        'DialogEnumValue_Character_BETTY': ['Betty'],
        'DialogEnumValue_Character_BILLSWORTH': ['Billsworth'],
        'DialogEnumValue_Character_BIRTHDAY_BANDIT': ['Birthday Bandit'],
        'DialogEnumValue_Character_BLACKJACK_DEALER': ['Blackjack Dealer'],
        'DialogEnumValue_Character_BLOODBUCKET': ['Bloodbucket'],
        'DialogEnumValue_Character_BLOODFLAP': ['Bloodflap'],
        'DialogEnumValue_Character_BLOODFLAPS_GANG': ['Garglespit'],
        'DialogEnumValue_Character_BLOODSHINE': ['Bloodshine'],
        'DialogEnumValue_Character_BOBO': ['King Bobo the Almighty'],
        'DialogEnumValue_Character_BONEY': ['Boney'],
        'DialogEnumValue_Character_BORMAN_NATES': ['Borman Nates'],
        'DialogEnumValue_Character_BOUNDARY_TURRET': ['Boundary Turret'],
        'DialogEnumValue_Character_BRICK': ['Brick', 'Evil Brick'],
        'DialogEnumValue_Character_BROTHER_CATUS': ['Brother Catus'],
        'DialogEnumValue_Character_BROTHER_MENDEL': ['Brother Mendel'],
        'DialogEnumValue_Character_BROTHER_SINON': ['Brother Sinon'],
        'DialogEnumValue_Character_BUD_LOADER': ['BUD Loader'],
        'DialogEnumValue_Character_BUREAUCRATIC_AI': ['Bureaucratic AI'],
        'DialogEnumValue_Character_BURGER_BOT': ['Burger Bot'],
        'DialogEnumValue_Character_BURTON': ['Burton Briggs'],
        'DialogEnumValue_Character_CAPTAIN_DAVIS': ['Cpt. Davis'],
        'DialogEnumValue_Character_CAPTAIN_DYER': ['Captain Dyer'],
        'DialogEnumValue_Character_CAPTAIN_HAUNT': ['Captain Haunt'],
        'DialogEnumValue_Character_CAPTAIN_TRAUNT': ['Captain Traunt'],
        'DialogEnumValue_Character_CARETAKER': ['Caretaker'],
        'DialogEnumValue_Character_CAROLINA': ['Carolina', 'Boss Keem'],
        'DialogEnumValue_Character_CASINO_BANDIT': ['Casino Looter'],
        'DialogEnumValue_Character_CASINO_BOT_1': ['Bureaucracy Bot'],
        'DialogEnumValue_Character_CASINO_BOT_DEALER_1': ['VIP Valet'],
        'DialogEnumValue_Character_CASUAL_BURNING_GAL': ['Ash'],
        'DialogEnumValue_Character_CASUAL_BURNING_GUY': ['Blaise'],
        'DialogEnumValue_Character_CECILIA': ['Cecilia'],
        'DialogEnumValue_Character_CELESTE': ['Celeste'],
        'DialogEnumValue_Character_CHADD': ['Chadd'],
        'DialogEnumValue_Character_CHEF_FRANK': ['Chef Frank'],
        'DialogEnumValue_Character_CHERB': ['Cherb'],
        'DialogEnumValue_Character_CHESS_ENFORCER': ['Mokdan Urgash'],
        'DialogEnumValue_Character_CIVILIAN': ['Promethean Civilian', 'Civilian'],
        'DialogEnumValue_Character_CLAPSTRUCTOR': ['Clapstructor'],
        'DialogEnumValue_Character_CLAPTRAP': ['Claptrap'],
        'DialogEnumValue_Character_CLARE_CONNORLY': ['Clare Connorly'],
        'DialogEnumValue_Character_CLATTER': ['The Abomination'],
        'DialogEnumValue_Character_CLAY': ['Clay'],
        'DialogEnumValue_Character_COMPUTERIZED_VOICE': ['Computerized Voice'],
        'DialogEnumValue_Character_CONDUCTOR': ['Conductor'],
        'DialogEnumValue_Character_COUNCIL_MEMBER_1': ['Councillor Molly'],
        'DialogEnumValue_Character_COUNCIL_MEMBER_2': ['Councillor Jeremiah'],
        'DialogEnumValue_Character_COV_BOUNCER': ['Bandit Zealot'],
        'DialogEnumValue_Character_COWARDLY_CHRIS': ['Chris'],
        'DialogEnumValue_Character_CRAD': ['Crad'],
        'DialogEnumValue_Character_CRAZY_EARL': ['Crazy Earl'],
        'DialogEnumValue_Character_CREW_MEMBER_01': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_02': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_03': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_06': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_08': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_09': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_10': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CREW_MEMBER_11': ['Sanctuary Crew Member'],
        'DialogEnumValue_Character_CRIMSON_RAIDER_NORMA': ['Norma'],
        'DialogEnumValue_Character_CRIMSON_RAIDER_SID': ['Sid'],
        'DialogEnumValue_Character_CRIVAN': ['Crivan'],
        'DialogEnumValue_Character_CROWD': ['Crowd'],
        'DialogEnumValue_Character_CURSE_OIL_CHARLATAN': ['Curse Oil Charlatan'],
        'DialogEnumValue_Character_DALTON': ['Dalton'],
        'DialogEnumValue_Character_DEADMAN': ['Deadman'],
        'DialogEnumValue_Character_DEAN': ['Dean'],
        'DialogEnumValue_Character_DEBRA': ['Debra'],
        'DialogEnumValue_Character_DEBT_COLLECTOR': ['The Debt Collector'],
        'DialogEnumValue_Character_DENTAL_DAN': ['Dental Dan'],
        'DialogEnumValue_Character_DERVIN': ['Dervin'],
        'DialogEnumValue_Character_DESSICA': ['Dessica'],
        'DialogEnumValue_Character_DEVILRIDER_LEADER': ['Devilrider Leader'],
        'DialogEnumValue_Character_DIGBY': ['Digby Vermouth'],
        'DialogEnumValue_Character_DINKLEBOT': ['Dinklebot'],
        'DialogEnumValue_Character_DJ_BLOOD': ['DJ Deadsk4g'],
        'DialogEnumValue_Character_DJ_MIDNIGHT': ['DJ Midnight'],
        'DialogEnumValue_Character_DJ_SPINSMOUTH': ['DJ Spinsmouth'],
        'DialogEnumValue_Character_DOC_STANLEY': ['Doc Stanley'],
        'DialogEnumValue_Character_DOMINO': ['Agent Domino'],
        'DialogEnumValue_Character_DOOMED_SCIENTIST': ['Doomed Scientist'],
        'DialogEnumValue_Character_DOORMAN': ['Doorman'],
        'DialogEnumValue_Character_DOUBLE_DEE_SEVEN': ['Agent Double Dee Seven'],
        'DialogEnumValue_Character_DOUBLE_DOWN_DOMINO': ['Double Down Domino'],
        'DialogEnumValue_Character_DRUNK_WILLIAM': ['Drunk William'],
        'DialogEnumValue_Character_DR_ENFORCER_1': ['Burly Pete', 'Benny', 'Dr. Dweeb Newton', 'Yosuke', 'Hoss'],
        'DialogEnumValue_Character_DR_GUNSLINGER_FEMALE_1': ['Delia', 'Leah the Canary', 'Trickshot Tracy'],
        'DialogEnumValue_Character_DR_GUNSLINGER_MALE_1': ['Billy the Skid', 'Deathless Dave', 'Unger', 'Slick Dill'],
        'DialogEnumValue_Character_DURTCH': ['Durtch'],
        'DialogEnumValue_Character_DYING_ATLAS_SOLDIER': ['Gonner'],
        'DialogEnumValue_Character_EADRIC_EDELHARD': ['Eadric Edelhard'],
        'DialogEnumValue_Character_EDEN_6_FEMALE_1': ['Edenian Civilian'],
        'DialogEnumValue_Character_EDEN_6_FEMALE_2': ['Edenian Civilian'],
        'DialogEnumValue_Character_EDEN_6_MALE_1': ['Edenian Civilian', 'Jon Ryan'],
        'DialogEnumValue_Character_EDEN_6_MALE_2': ['Edenian Civilian', 'Kyle'],
        'DialogEnumValue_Character_EDGREN': ['Edgren', 'Lord of Skags'],
        'DialogEnumValue_Character_EISTA': ['Eista'],
        'DialogEnumValue_Character_ELEANOR': ['Eleanor'],
        'DialogEnumValue_Character_ELI': ['Eli'],
        'DialogEnumValue_Character_EL_DRAGON_JR': ['El DragĂłn Jr.'],
        'DialogEnumValue_Character_EL_DRAGON_JR_RAGE': ['El DragĂłn Jr.'],
        'DialogEnumValue_Character_EMBER': ['Ember'],
        'DialogEnumValue_Character_ENFORCER_1': ['Enforcer', 'Muldock the Anointed', 'Contestant', 'Toothshine The Third', 'Anointed Enforcer', 'Badass Enforcer', 'Turnkey Tim'],
        'DialogEnumValue_Character_ENSIGN_BEN': ['Ensign Ben'],
        'DialogEnumValue_Character_ENSIGN_LARRY': ['Ensign Larry'],
        'DialogEnumValue_Character_ENSIGN_RENEE': ['Ensign Renee'],
        'DialogEnumValue_Character_ENSIGN_RYAN': ['Ensign Ryan'],
        'DialogEnumValue_Character_ESTER': ['Ester'],
        'DialogEnumValue_Character_Ellie': ['Ellie'],
        'DialogEnumValue_Character_FACILITY_VOICE': ['Facility Voice'],
        'DialogEnumValue_Character_FAILUREBOT': ['Failurebot'],
        'DialogEnumValue_Character_FB_MUMBLER_MALE_1': ['Gideon'],
        'DialogEnumValue_Character_FIELD_MARSHAL_KAZIAK': ['Kaziak'],
        'DialogEnumValue_Character_FILM_BUFF': ['Buff'],
        'DialogEnumValue_Character_FOREMAN': ['Foreman'],
        'DialogEnumValue_Character_FRANCIS': ['Francis'],
        'DialogEnumValue_Character_FREDDIE': ['Freddie'],
        'DialogEnumValue_Character_GADDY': ['Gaddy'],
        'DialogEnumValue_Character_GAIGE': ['Gaige'],
        'DialogEnumValue_Character_GAMBLIN_MAN_STAN': ["Gamblin' Man Stan"],
        'DialogEnumValue_Character_GARY': ['Gary'],
        'DialogEnumValue_Character_GAYLE': ['Gayle'],
        'DialogEnumValue_Character_GENERAL_MARKS': ['General Marks'],
        'DialogEnumValue_Character_GENERAL_TRAUNT': ['General Traunt'],
        'DialogEnumValue_Character_GENIVIV': ['GenIVIV'],
        'DialogEnumValue_Character_GLENN': ['Glenn'],
        'DialogEnumValue_Character_GODDESS_STATUE': ['Goddess Statue'],
        'DialogEnumValue_Character_GOLDEN_BULLION': ['Golden Bullion'],
        'DialogEnumValue_Character_GOLIATH_1': ['Goliath', 'Blargmaw', 'Agent Double Dee Seven', 'Projector Guard', 'Warden', 'Anointed Goliath', 'Badass Goliath', "Li'l Goliath"],
        'DialogEnumValue_Character_GOLIATH_RAGE_1': ['Raging Badass Goliath', "Mega Raging Li'l Goliath", 'Raging Goliath', 'Blargmaw', 'Raging Warden', 'Anointed Goliath'],
        'DialogEnumValue_Character_GOON_1': ['Hag', 'Anointed Hag', 'Badass Hag'],
        'DialogEnumValue_Character_GOREBOX': ['Gorebox'],
        'DialogEnumValue_Character_GORE_GIRLS': ['Gore GIrls'],
        'DialogEnumValue_Character_GRAND_ARCHIVIST': ['Grand Archivist'],
        'DialogEnumValue_Character_GRANNY': ['Granny'],
        'DialogEnumValue_Character_GRAWN_1': ['Procurer', 'Grawn'],
        'DialogEnumValue_Character_GROGMOUTH': ['Grogmouth'],
        'DialogEnumValue_Character_GROUSE': ['Grouse'],
        'DialogEnumValue_Character_GUSTAV': ['Gustav'],
        'DialogEnumValue_Character_HAG_MOTHER': ['Mother Fearest'],
        'DialogEnumValue_Character_HALLAN': ['Hallan'],
        'DialogEnumValue_Character_HAMMERLOCK': ['Hammerlock'],
        'DialogEnumValue_Character_HANDSOME_JACK': ['Handsome Jack'],
        'DialogEnumValue_Character_HANDSOME_JACKIE': ['Handsome Jackie'],
        'DialogEnumValue_Character_HARDIN': ['Hardin'],
        'DialogEnumValue_Character_HARRIET': ['Harriet'],
        'DialogEnumValue_Character_HARTFORD': ['Hartford'],
        'DialogEnumValue_Character_HEAVY_1': ['Pyrotech Heavy', 'Lieutenant Preston', 'Badass Powerhouse Heavy'],
        'DialogEnumValue_Character_HECKLE': ['Heckle'],
        'DialogEnumValue_Character_HINA': ['Hina'],
        'DialogEnumValue_Character_HIPHONIUS': ['Hiphonius'],
        'DialogEnumValue_Character_HIRSCHIM': ['Hirschim'],
        'DialogEnumValue_Character_HISTORIAN': ['Historian'],
        'DialogEnumValue_Character_HITCH': ['Hitch'],
        'DialogEnumValue_Character_HIZZEN': ['Hizzen'],
        'DialogEnumValue_Character_HOLDER': ['Holder'],
        'DialogEnumValue_Character_HOLLOWAY': ['Holloway'],
        'DialogEnumValue_Character_HOT_KARL': ['Hot Karl'],
        'DialogEnumValue_Character_HYDE': ['Hyde'],
        'DialogEnumValue_Character_HYPERION_VOICE': ['Hyperion Voice'],
        'DialogEnumValue_Character_IRA': ['Ira'],
        'DialogEnumValue_Character_IRIS': ['Iris'],
        'DialogEnumValue_Character_JABBER_TRACKER': ['Rogue Tracker'],
        'DialogEnumValue_Character_JACKBOT': ['Jackpot'],
        'DialogEnumValue_Character_JAKOBS_AI': ['Jakobs AI'],
        'DialogEnumValue_Character_JANICE_CARDALIA': ['Janice Cardalia'],
        'DialogEnumValue_Character_JAQIE': ['Jaquie'],
        'DialogEnumValue_Character_JEANNA': ['Jeanna'],
        'DialogEnumValue_Character_JERICK': ['Jerick'],
        'DialogEnumValue_Character_JOEY_ULTRAVIOLET': ['Joey Ultraviolet'],
        'DialogEnumValue_Character_JOSEY': ['Josey'],
        'DialogEnumValue_Character_JOY': ['Joy'],
        'DialogEnumValue_Character_JUDGE_HIGHTOWER': ['Judge Hightower'],
        'DialogEnumValue_Character_JUNO': ['Juno'],
        'DialogEnumValue_Character_KATAGAWAJR': ['Katagawa Jr.'],
        'DialogEnumValue_Character_KATAGAWA_BALL': ['Katagawa Ball'],
        'DialogEnumValue_Character_KAY': ['Kay'],
        'DialogEnumValue_Character_KIDNAPPER': ['Kidnapper'],
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_1': ['Fangirl'],
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_2': ['Fangirl'],
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_3': ['Fangirl'],
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_4': ['Fangirl'],
        'DialogEnumValue_Character_KILLAVOLT_VIDEO': ['Killavolt'],
        'DialogEnumValue_Character_KORMASH': ['Kormash'],
        'DialogEnumValue_Character_KRIEG': ['Krieg'],
        'DialogEnumValue_Character_KRIEG_PSYCHO': ['Psycho Krieg', 'King Krieg'],
        'DialogEnumValue_Character_KRIEG_SANE': ['Sane Krieg'],
        'DialogEnumValue_Character_KillaVolt': ['Killavolt'],
        'DialogEnumValue_Character_LANA': ["Lana Sh'ani"],
        'DialogEnumValue_Character_LARK': ['Lark'],
        'DialogEnumValue_Character_LAROLD': ['Ensign Ben'],
        'DialogEnumValue_Character_LASER_TECHNICIAN': ['Laser Technician'],
        'DialogEnumValue_Character_LASHLEY': ['Lashley'],
        'DialogEnumValue_Character_LEAH_HART': ['Leah Hart'],
        'DialogEnumValue_Character_LENNY': ['Lenny'],
        'DialogEnumValue_Character_LILITH': ['Lilith', 'Evil Lilith'],
        'DialogEnumValue_Character_LIZZIE': ['Lizzie'],
        'DialogEnumValue_Character_LOADER_1': ['DTF Loader', 'Loader Bot'],
        'DialogEnumValue_Character_LORELEI': ['Unknown'],
        'DialogEnumValue_Character_LT_WELLS': ['Lt. Wells'],
        'DialogEnumValue_Character_MALECH_1': ['Malech'],
        'DialogEnumValue_Character_MALIWAN_PATROLMAN': ['Maliwan Patrolman'],
        'DialogEnumValue_Character_MANCUBUS': ['Mancubus Bloodtooth'],
        'DialogEnumValue_Character_MARCUS': ['Marcus'],
        'DialogEnumValue_Character_MARK': ['Mark'],
        'DialogEnumValue_Character_MARTYR': ['Martyr'],
        'DialogEnumValue_Character_MAURICE': ['Maurice'],
        'DialogEnumValue_Character_MAX_SKY': ['Max Sky'],
        'DialogEnumValue_Character_MAYA': ['Maya'],
        'DialogEnumValue_Character_MAYOR': ['The Mayor'],
        'DialogEnumValue_Character_MA_HONEYWELL': ['Ma Honeywell'],
        'DialogEnumValue_Character_MCSMUGGER': ['McSmugger'],
        'DialogEnumValue_Character_MECH_1': ['Hoplite'],
        'DialogEnumValue_Character_MESSY_BREAKUP': ['Messy Breakup'],
        'DialogEnumValue_Character_MICKEY_TRICKS': ['Mickey Tricks'],
        'DialogEnumValue_Character_MILES': ['Prof. Miles Brown'],
        'DialogEnumValue_Character_MILLER': ['Miller'],
        'DialogEnumValue_Character_MILO_THE_MIME': ['Milo the Mime'],
        'DialogEnumValue_Character_MONK_1': ['Athenas Monk'],
        'DialogEnumValue_Character_MONTGOMERY_JAKOBS': ['Montgomery Jakobs'],
        'DialogEnumValue_Character_MORDECAI': ['Mordecai', 'Evil Mordecai'],
        'DialogEnumValue_Character_MOUTHPIECE': ['Mouthpiece'],
        'DialogEnumValue_Character_MURL': ['Murl'],
        'DialogEnumValue_Character_Moxxi': ['Moxxi'],
        'DialogEnumValue_Character_NAILS': ['Nails'],
        'DialogEnumValue_Character_NAOKO': ['Unknown', 'Naoko'],
        'DialogEnumValue_Character_NETTLE': ['Nettle'],
        'DialogEnumValue_Character_NEW-U': ['New-U'],
        'DialogEnumValue_Character_NEWS_ANCHOR': ['News Anchor', 'Shanneth Kyrie'],
        'DialogEnumValue_Character_NIBBLENOMICON': ['Nibblenomicon'],
        'DialogEnumValue_Character_NILLY': ['Nilly'],
        'DialogEnumValue_Character_NOG_1': ['NOG', 'Gigamind', 'Runaway NOG', 'Badass NOG'],
        'DialogEnumValue_Character_NPC_WALLA': ['Unintelligible Chatter'],
        'DialogEnumValue_Character_NYRIAD': ['Nyriad'],
        'DialogEnumValue_Character_OFFICER_TED': ['Officer Ted'],
        'DialogEnumValue_Character_OLD_PETE': ['Old Pete'],
        'DialogEnumValue_Character_OLETTA': ['Oletta'],
        'DialogEnumValue_Character_OMEN': ['Omen'],
        'DialogEnumValue_Character_OVERSEER': ['Overseer'],
        'DialogEnumValue_Character_OVERSPHERE': ['Oversphere', 'Dark Oversphere'],
        'DialogEnumValue_Character_PAIN': ['Pain'],
        'DialogEnumValue_Character_PANDORA_FEMALE_1': ['Pandoran Civilian'],
        'DialogEnumValue_Character_PANDORA_FEMALE_2': ['Pandoran Civilian'],
        'DialogEnumValue_Character_PANDORA_MALE_1': ['Pandoran Civilian'],
        'DialogEnumValue_Character_PANDORA_MALE_2': ['Pandoran Civilian'],
        'DialogEnumValue_Character_PAPPY': ['Pappy'],
        'DialogEnumValue_Character_PARKER': ['Parker'],
        'DialogEnumValue_Character_PA_HONEYWELL': ['Pa Honeywell'],
        'DialogEnumValue_Character_PELLIYA': ['Pelliya'],
        'DialogEnumValue_Character_PICKED_ON_GUY': ['Chancey'],
        'DialogEnumValue_Character_PL_BEASTMASTER': ['FL4K'],
        'DialogEnumValue_Character_PL_GUNNER': ['Moze'],
        'DialogEnumValue_Character_PL_OPERATIVE': ['Zane'],
        'DialogEnumValue_Character_PL_SIREN': ['Amara'],
        'DialogEnumValue_Character_PORTAPOTTY_BANDIT': ['Trashmouth'],
        'DialogEnumValue_Character_POWER_TROOPERS': ['Power Troopers'],
        'DialogEnumValue_Character_PRETTY_BOY': ['Pretty Boy'],
        'DialogEnumValue_Character_PRISA': ['Prisa'],
        'DialogEnumValue_Character_PRISCILLA': ['Priscilla'],
        'DialogEnumValue_Character_PROMETHEA_FEMALE_1': ['Promethean Civilian'],
        'DialogEnumValue_Character_PROMETHEA_FEMALE_2': ['Promethean Civilian'],
        'DialogEnumValue_Character_PROMETHEA_MALE_1': ['Promethean Civilian'],
        'DialogEnumValue_Character_PROMETHEA_MALE_2': ['Promethean Civilian'],
        'DialogEnumValue_Character_PROSPECTOR': ['Prospector'],
        'DialogEnumValue_Character_PSYCHOREAVER': ['Psychoreaver'],
        'DialogEnumValue_Character_PSYCHO_FEMALE_1': ['Psycho', 'Gutshine', 'Mommy Dearish'],
        'DialogEnumValue_Character_PSYCHO_KILLER': ['Psycho Killer'],
        'DialogEnumValue_Character_PSYCHO_MALE_1': ['Psycho', 'Completely Sane Sid', 'Long Arm the Smasher', 'Pinglover Psycho', 'Anointed Psycho', 'Badass Psycho', 'Sleeping Dan', 'Bathboy'],
        'DialogEnumValue_Character_PUNK_FEMALE_1': ['Fanatic', 'Bloodclaw', 'Gang Leader', 'Gatekeeper', 'Hater Punk', 'Anointed Fanatic', 'Badass Fanatic'],
        'DialogEnumValue_Character_PUNK_FEMALE_2': ['Fanatic', 'Sheega'],
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_2': ['Audience Member'],
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_4': ['Audience Member'],
        'DialogEnumValue_Character_PUNK_MALE_1': ['Fanatic', 'Boney', 'Killer Punk', 'Longshank', 'Rohner', 'Anointed Fanatic', 'Badass Fanatic'],
        'DialogEnumValue_Character_PUNK_MALE_2': ['Fanatic'],
        'DialogEnumValue_Character_QUIETFOOT': ['Agent Quietfoot'],
        'DialogEnumValue_Character_QUINN': ['Quinn'],
        'DialogEnumValue_Character_RAKKMAN': ["I'm Rakkman"],
        'DialogEnumValue_Character_RAMSDEN': ['Ramsden'],
        'DialogEnumValue_Character_RANCHER': ['Rancher'],
        'DialogEnumValue_Character_RAZOR_TOOTH': ['Razor Tooth'],
        'DialogEnumValue_Character_REAPER': ['Reaper'],
        'DialogEnumValue_Character_REAPER_JONES': ['Reaper Jones'],
        'DialogEnumValue_Character_REBA': ['Reba'],
        'DialogEnumValue_Character_RECRUITMENT_BANDIT': ['Bandit Zealot'],
        'DialogEnumValue_Character_RECRUITMENT_BANDIT_2': ['Bandit Zealot'],
        'DialogEnumValue_Character_REDEEMER': ['The Seer'],
        'DialogEnumValue_Character_RED_JABBER': ['Red Jabber'],
        'DialogEnumValue_Character_RHYS': ['Rhys', 'Rhys-Ball'],
        'DialogEnumValue_Character_ROADDOG': ['Road Dog'],
        'DialogEnumValue_Character_ROADDOG_RAGE': ['Raging Road Dog'],
        'DialogEnumValue_Character_ROSE': ['Rose'],
        'DialogEnumValue_Character_ROSE_S_MOTHER': ["Rose's Mother"],
        'DialogEnumValue_Character_RUDY_VARLOPE': ['Rudy Varlope'],
        'DialogEnumValue_Character_SALTY_JERMS': ['Salty Jerms'],
        'DialogEnumValue_Character_SALVADOR': ['Salvador'],
        'DialogEnumValue_Character_SANDY_HART': ['Sandy Hart'],
        'DialogEnumValue_Character_SATO': ['Sato'],
        'DialogEnumValue_Character_SAURIAN_HIVEMIND': ['Scaleon Hivemind'],
        'DialogEnumValue_Character_SCRAPTRAP': ['Scraptrap'],
        'DialogEnumValue_Character_SCRAPYARD_BANDIT_1': ['Bandit Zealot'],
        'DialogEnumValue_Character_SCRUNTER': ['Scrunter'],
        'DialogEnumValue_Character_SECURITYMADAM': ['Orbital Security'],
        'DialogEnumValue_Character_SECURITY_TERMINAL': ['Security Terminal'],
        'DialogEnumValue_Character_SERGEANT_HEADLEY': ['Sgt. Headly'],
        'DialogEnumValue_Character_SERGEANT_HIGGWINK': ['Sgt. Higgwink'],
        'DialogEnumValue_Character_SERGEANT_HOMINS': ['Sgt. Homins'],
        'DialogEnumValue_Character_SERVICE_BOT': ['Service Bot'],
        'DialogEnumValue_Character_SERVICE_BOT_FIRE_1': ['Fire Bot'],
        'DialogEnumValue_Character_SERVICE_BOT_LAW_1': ['Deputy Bot', 'Corrupt Law Bot', 'Dirty Cop', 'Johnny Law Bot'],
        'DialogEnumValue_Character_SERVICE_BOT_MED_1': ['EMS BOT', 'EMS Bot'],
        'DialogEnumValue_Character_SERVICE_BOT_SWAT_1': ['Sheriff Bot'],
        'DialogEnumValue_Character_SERVICE_BOT_WMS_1': ['Recycler Bot', 'Lark'],
        'DialogEnumValue_Character_SHADY_DEALER': ['Shady Dealer'],
        'DialogEnumValue_Character_SHELLY': ['Shelly'],
        'DialogEnumValue_Character_SHERIFF': ['Sheriff'],
        'DialogEnumValue_Character_SHIV': ['Shiv'],
        'DialogEnumValue_Character_SIBLINGS_WALLA': ['Unintelligible Chatter'],
        'DialogEnumValue_Character_SILVA': ['Silvan'],
        'DialogEnumValue_Character_SKYLER': ['Skyman'],
        'DialogEnumValue_Character_SLIM': ['Slim'],
        'DialogEnumValue_Character_SLOTH': ['Sloth'],
        'DialogEnumValue_Character_SMUGGLER_1': ['Smuggler 1'],
        'DialogEnumValue_Character_SMUGGLER_2': ['Smuggler 2'],
        'DialogEnumValue_Character_SNAKE_EYES_LEADER': ['Snake Eyes Leader'],
        'DialogEnumValue_Character_SOAPY_STEVE': ['Soapy Steve'],
        'DialogEnumValue_Character_SOURBONES': ['Sour Bones'],
        'DialogEnumValue_Character_SPARROW': ['Sparrow'],
        'DialogEnumValue_Character_STANK_KNEE': ['Stank Knee'],
        'DialogEnumValue_Character_STANLEY': ['Stanley'],
        'DialogEnumValue_Character_STEEL_DRAGON': ['Steel Dragon of Eternal Pain'],
        'DialogEnumValue_Character_STEPHIE': ['Stephie'],
        'DialogEnumValue_Character_STICKLY': ['Stickly'],
        'DialogEnumValue_Character_SUN_SMASHER_CLAN': ['Sun Smasher Clan Members'],
        'DialogEnumValue_Character_SYLESTRO': ['Sylestro'],
        'DialogEnumValue_Character_TAMMY_TWO_GUNS': ['Tanya'],
        'DialogEnumValue_Character_TANNER': ['Tanner'],
        'DialogEnumValue_Character_TANNIS': ['Tannis'],
        'DialogEnumValue_Character_TANYA': ['Tanya'],
        'DialogEnumValue_Character_TEDIORE': ['Tediore'],
        'DialogEnumValue_Character_TEDIORE_GUN_PAT': ['P.A.T.', "P.A.T.'s Baby"],
        'DialogEnumValue_Character_TERN': ['Tern'],
        'DialogEnumValue_Character_TERROR': ['Pain'],
        'DialogEnumValue_Character_TERRY': ['Terry'],
        'DialogEnumValue_Character_THADDEUS': ['Sir Thaddeus'],
        'DialogEnumValue_Character_THEATER_OWNER': ['Theater Owner'],
        'DialogEnumValue_Character_THE_UNSTOPPABLE': ['The Unstoppable?'],
        'DialogEnumValue_Character_THE_UNSTOPPABLE_RAGE': ['The Unstoppable'],
        'DialogEnumValue_Character_THIRD_RAIL': ['Third Rail'],
        'DialogEnumValue_Character_THUNK': ['Thunk'],
        'DialogEnumValue_Character_TIMOTHY': ['Timothy Lawrence', 'Unknown'],
        'DialogEnumValue_Character_TINA': ['Tina'],
        'DialogEnumValue_Character_TINK_1': ['Tink', 'Big Donny', 'Dave', 'Hater Punk', 'Interrogator', 'Anointed Tink', 'Badass Tink'],
        'DialogEnumValue_Character_TINK_LOOT_1': ['Loot Tink', 'Under Taker'],
        'DialogEnumValue_Character_TINK_PSYCHO_1': ['Psycho Tink'],
        'DialogEnumValue_Character_TITUS': ['Titus'],
        'DialogEnumValue_Character_TODD_BARLOS': ['Todd Barlos'],
        'DialogEnumValue_Character_TONGUE_BANDIT': ['Tongue Bandit'],
        'DialogEnumValue_Character_TONY': ['Tony Bordel'],
        'DialogEnumValue_Character_TORGUE': ['Torgue'],
        'DialogEnumValue_Character_TOWER_DEFENDER': ['Atlas Soldier'],
        'DialogEnumValue_Character_TOWNSFOLK_FEMALE_1': ['Ari', 'Jerica', 'Yuko'],
        'DialogEnumValue_Character_TOWNSFOLK_FEMALE_2': ['Joely', 'Kiko', 'Ko', 'Leanne'],
        'DialogEnumValue_Character_TOWNSFOLK_FEMALE_3': ['Eudice'],
        'DialogEnumValue_Character_TOWNSFOLK_MALE_1': ['Ferris', 'Gus', 'Ori'],
        'DialogEnumValue_Character_TOWNSFOLK_MALE_2': ['Cato', 'Herb', 'Kenji', 'Tarou', 'Tedden'],
        'DialogEnumValue_Character_TRASHLANTIS_FEMALE_1': ['Trashlantis Citizen'],
        'DialogEnumValue_Character_TRENT_THE_SLUT': ['Trent the Slut'],
        'DialogEnumValue_Character_TRICKSY_NICK': ['Tricksy Nick'],
        'DialogEnumValue_Character_TROOPER_1': ['Assault Trooper', 'Caffeine Carl', 'Coffee Commander', 'Maliwan Soldier', 'Insomniac Greg', 'Interrogator', 'Maliwan', 'Rax', 'Badass Trooper', 'Tim'],
        'DialogEnumValue_Character_TROOPER_2': ['Assault Trooper', 'Undercover Atlas Agent', 'Coffee Runner', 'Max', 'Wired Will'],
        'DialogEnumValue_Character_TROY_CALYPSO': ['Troy'],
        'DialogEnumValue_Character_TUMORHEAD': ['Tumorhead'],
        'DialogEnumValue_Character_TUNNEL_DWELLER': ['Tunnel Dweller'],
        'DialogEnumValue_Character_TYPHON_DELEON': ['Unknown', 'Typhon DeLeon'],
        'DialogEnumValue_Character_TYREEN_CALYPSO': ['Tyreen'],
        'DialogEnumValue_Character_UNRULY_BAR_PATRON': ['Unruly Bar Patron'],
        'DialogEnumValue_Character_VAUGHN': ['Unknown', 'Vaughn'],
        'DialogEnumValue_Character_VERCUVIO': ['Vercuvio'],
        'DialogEnumValue_Character_VERONICA': ['VR-0N1CA'],
        'DialogEnumValue_Character_VIC': ['Vic'],
        'DialogEnumValue_Character_VICS_HEAD': ['Vic'],
        'DialogEnumValue_Character_VIDEO_NARRATOR': ['Narrator'],
        'DialogEnumValue_Character_VINCENT': ['Vincent'],
        'DialogEnumValue_Character_WAINWRIGHT': ['Wainwright Jakobs'],
        'DialogEnumValue_Character_WALLA': ['Gamblers'],
        'DialogEnumValue_Character_WALTAR': ['Walter'],
        'DialogEnumValue_Character_WANDERER': ['Wanderer'],
        'DialogEnumValue_Character_WARTY': ['Warty Prime'],
        'DialogEnumValue_Character_WATCHER': ['Overseer'],
        'DialogEnumValue_Character_WEASEL': ['Weasel'],
        'DialogEnumValue_Character_WEDDING_GUEST': ['Wedding Guest'],
        'DialogEnumValue_Character_WES': ['Wes'],
        'DialogEnumValue_Character_WICK': ['Wick'],
        'DialogEnumValue_Character_WILD_CARD_LEADER': ['Wild Card Leader'],
        'DialogEnumValue_Character_WITNESS_1': ['Witness 1'],
        'DialogEnumValue_Character_WITNESS_2': ['Witness 2'],
        'DialogEnumValue_Character_WREN': ['Wren'],
        'DialogEnumValue_Character_YOUNG_JED': ['Young Jed'],
        'DialogEnumValue_Character_YOUNG_ROSE': ['Rose'],
        'DialogEnumValue_Character_YVAN': ['Yvan'],
        'DialogEnumValue_Character_ZAHNZI': ['Zahnzi Kall'],
        'DialogEnumValue_Character_ZER0': ['Zer0'],
        'DialogEnumValue_Character_ZIFF': ['Ziff'],
    }

    DialogEnumValueNames = {
        'DialogEnumValue_CharQualifier_DTF_LOADER': 'DTF Loader',
        'DialogEnumValue_Character_ACE': 'Ace Baron',
        'DialogEnumValue_Character_ADI': 'Adi',
        'DialogEnumValue_Character_AD_CUSTOMER': 'Customer',
        'DialogEnumValue_Character_ALKONOST': 'Alkonost',
        'DialogEnumValue_Character_ALL_IN_ALLAN': 'All-In Allan',
        'DialogEnumValue_Character_ANGEL': 'Angel',
        'DialogEnumValue_Character_ARCHER_ROWE': 'Archer Rowe',
        'DialogEnumValue_Character_ARCHIMEDES': 'Archimedes',
        'DialogEnumValue_Character_ASSASSIN_1': 'Barnabus',
        'DialogEnumValue_Character_ATLAS_CHATTER': 'Atlas Soldier Chatter',
        'DialogEnumValue_Character_ATLAS_SOLDIER': 'Atlas Soldier',
        'DialogEnumValue_Character_ATLAS_SOLDIER_1': 'Liam',
        'DialogEnumValue_Character_ATLAS_SOLDIER_2': 'Atlas Soldier',
        'DialogEnumValue_Character_ATLAS_SOLDIER_BAR_PATRON': 'Atlas Bar Patron',
        'DialogEnumValue_Character_ATOMIC': 'Atomic',
        'DialogEnumValue_Character_AURELIA': 'Aurelia',
        'DialogEnumValue_Character_AVA': 'Ava',
        'DialogEnumValue_Character_AXTON': 'Axton',
        'DialogEnumValue_Character_AZALEA': 'Azalea',
        'DialogEnumValue_Character_BABY': 'Baby',
        'DialogEnumValue_Character_BALDRIN': 'Baldrin',
        'DialogEnumValue_Character_BALEX': 'BALEX',
        'DialogEnumValue_Character_BANDIT': 'Bandit',
        'DialogEnumValue_Character_BANDIT_1': 'Bandit',
        'DialogEnumValue_Character_BANDIT_2': 'Bandit',
        'DialogEnumValue_Character_BANDIT_3': 'Bandit',
        'DialogEnumValue_Character_BANDIT_BATTLE_WAVE': 'Bandits',
        'DialogEnumValue_Character_BANDIT_BIRTHDAY_WALLA': 'Bandits',
        'DialogEnumValue_Character_BANDIT_MALE_1': 'Looter',
        'DialogEnumValue_Character_BANDIT_MALE_2': 'Looter',
        'DialogEnumValue_Character_BANDIT_MEDLEY': 'Bandits',
        'DialogEnumValue_Character_BANDIT_WALLA': 'Bandits',
        'DialogEnumValue_Character_BANDIT_ZEALOT': 'Bandit Zealot',
        'DialogEnumValue_Character_BARISTA_BOT': 'Barista Bot',
        'DialogEnumValue_Character_BARON_NOGGIN': 'Baron Noggin',
        'DialogEnumValue_Character_BAR_PATRON': 'Bar Patron',
        'DialogEnumValue_Character_BEANS': 'Private Beans',
        'DialogEnumValue_Character_BEATRICE': 'Beatrice',
        'DialogEnumValue_Character_BEAU': 'Beau',
        'DialogEnumValue_Character_BENEDICT': 'Dr. Benedict',
        'DialogEnumValue_Character_BIRTHDAY_BANDIT': 'Birthday Bandit',
        'DialogEnumValue_Character_BLACKJACK_DEALER': 'Blackjack Dealer',
        'DialogEnumValue_Character_BLACK_GROG': 'Black Grog',
        'DialogEnumValue_Character_BLOODBUCKET': 'Bloodbucket',
        'DialogEnumValue_Character_BLOODFLAP': 'Bloodflap',
        'DialogEnumValue_Character_BLOODFLAPS_GANG': 'Garglespit',
        'DialogEnumValue_Character_BLOODSHINE': 'Bloodshine',
        'DialogEnumValue_Character_BLUE_VARKID': 'Blue Varkid',
        'DialogEnumValue_Character_BOBO': 'King Bobo the Almighty',
        'DialogEnumValue_Character_BONEY': 'Boney',
        'DialogEnumValue_Character_BORMAN_NATES': 'Borman Nates',
        'DialogEnumValue_Character_BOUNDARY_TURRET': 'Boundary Turret',
        'DialogEnumValue_Character_BRICK': 'Brick',
        'DialogEnumValue_Character_BROTHER_CATUS': 'Brother Catus',
        'DialogEnumValue_Character_BROTHER_MENDEL': 'Brother Mendel',
        'DialogEnumValue_Character_BROTHER_SINON': 'Brother Sinon',
        'DialogEnumValue_Character_BUREAUCRATIC_AI': 'Bureaucratic AI',
        'DialogEnumValue_Character_BURGER_BOT': 'Burger Bot',
        'DialogEnumValue_Character_BURTON': 'Burton Briggs',
        'DialogEnumValue_Character_CAPTAIN_DAVIS': 'Cpt. Davis',
        'DialogEnumValue_Character_CAPTAIN_DYER': 'Captain Dyer',
        'DialogEnumValue_Character_CAPTAIN_TRAUNT': 'Captain Traunt',
        'DialogEnumValue_Character_CARETAKER': 'Caretaker',
        'DialogEnumValue_Character_CASINO_BOT_1': 'Bureaucracy Bot',
        'DialogEnumValue_Character_CASINO_BOT_DEALER_1': 'VIP Valet',
        'DialogEnumValue_Character_CECILIA': 'Cecilia',
        'DialogEnumValue_Character_CELESTE': 'Celeste',
        'DialogEnumValue_Character_CHADD': 'Chadd',
        'DialogEnumValue_Character_CHEF_FRANK': 'Chef Frank',
        'DialogEnumValue_Character_CIVILIAN': 'Civilian',
        'DialogEnumValue_Character_CLAPETTE': 'VR-0N1CA',
        'DialogEnumValue_Character_CLAPSTRUCTOR': 'Clapstructor',
        'DialogEnumValue_Character_CLAPTRAP': 'Claptrap',
        'DialogEnumValue_Character_CLARE_CONNORLY': 'Clare Connorly',
        'DialogEnumValue_Character_CLATTER': 'The Abomination',
        'DialogEnumValue_Character_CLAY': 'Clay',
        'DialogEnumValue_Character_COMPUTERIZED_VOICE': 'Computerized Voice',
        'DialogEnumValue_Character_CONSTRUCTOR_1': 'Constructor',
        'DialogEnumValue_Character_COOPER': 'Cooper',
        'DialogEnumValue_Character_CORE_DADDY': 'Core Daddy',
        'DialogEnumValue_Character_COV_BOUNCER': 'Bandit Zealot',
        'DialogEnumValue_Character_CRAD': 'Crad',
        'DialogEnumValue_Character_CRAZY_EARL': 'Crazy Earl',
        'DialogEnumValue_Character_CREW_MEMBER_01': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_02': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_03': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_04': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_05': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_06': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_07': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_08': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_09': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_10': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CREW_MEMBER_11': 'Sanctuary Crew Member',
        'DialogEnumValue_Character_CRIMSON_RAIDER_NORMA': 'Norma',
        'DialogEnumValue_Character_CRIMSON_RAIDER_SID': 'Sid',
        'DialogEnumValue_Character_CURSE_OIL_CHARLATAN': 'Curse Oil Charlatan',
        'DialogEnumValue_Character_DALTON': 'Dalton',
        'DialogEnumValue_Character_DEADMAN': 'Deadman',
        'DialogEnumValue_Character_DEAN': 'Dean',
        'DialogEnumValue_Character_DEBT_COLLECTOR': 'The Debt Collector',
        'DialogEnumValue_Character_DEFENSE_TECHNICIAN': 'Atlas Soldier',
        'DialogEnumValue_Character_DENTAL_DAN': 'Dental Dan',
        'DialogEnumValue_Character_DEVILRIDER_LEADER': 'Devilrider Leader',
        'DialogEnumValue_Character_DIGBY': 'Digby Vermouth',
        'DialogEnumValue_Character_DINKLEBOT': 'Dinklebot',
        'DialogEnumValue_Character_DISCLAIMER_GUY': 'Disclaimer',
        'DialogEnumValue_Character_DJ_BLOOD': 'DJ Deadsk4g',
        'DialogEnumValue_Character_DOC_STANLEY': 'Doc Stanley',
        'DialogEnumValue_Character_DOMINO': 'Agent Domino',
        'DialogEnumValue_Character_DOOMED_SCIENTIST': 'Doomed Scientist',
        'DialogEnumValue_Character_DOORMAN': 'Doorman',
        'DialogEnumValue_Character_DOUBLE_DEE_SEVEN': 'Agent Double Dee Seven',
        'DialogEnumValue_Character_DOUBLE_DOWN_DOMINO': 'Double Down Domino',
        'DialogEnumValue_Character_DR_ENFORCER_1': 'Yosuke',
        'DialogEnumValue_Character_DR_GUNSLINGER_MALE_1': 'Unger',
        'DialogEnumValue_Character_DUFRANE': 'Dalton',
        'DialogEnumValue_Character_DURTCH': 'Durtch',
        'DialogEnumValue_Character_DYER_AI': 'Captain Dyer AI',
        'DialogEnumValue_Character_DYING_ATLAS_SOLDIER': 'Gonner',
        'DialogEnumValue_Character_EADRIC_EDELHARD': 'Eadric Edelhard',
        'DialogEnumValue_Character_EDEN_6_FEMALE_1': 'Edenian Civilian',
        'DialogEnumValue_Character_EDEN_6_FEMALE_2': 'Edenian Civilian',
        'DialogEnumValue_Character_EDEN_6_MALE_1': 'Jon Ryan',
        'DialogEnumValue_Character_EDEN_6_MALE_2': 'Kyle',
        'DialogEnumValue_Character_EDGREN': 'Lord of Skags',
        'DialogEnumValue_Character_EISTA': 'Eista',
        'DialogEnumValue_Character_ELEANOR': 'Eleanor',
        'DialogEnumValue_Character_ELI': 'Eli',
        'DialogEnumValue_Character_EL_DRAGON_JR': 'El Dragón Jr.',
        'DialogEnumValue_Character_EL_DRAGON_JR_RAGE': 'El Dragón Jr.',
        'DialogEnumValue_Character_EMBER': 'Ember',
        'DialogEnumValue_Character_ENFORCER_1': 'Contestant',
        'DialogEnumValue_Character_ENSIGN_RYAN': 'Ensign Ryan',
        'DialogEnumValue_Character_ESTER': 'Ester',
        'DialogEnumValue_Character_EchoLog_KillaVolt': 'Killavolt',
        'DialogEnumValue_Character_Ellie': 'Ellie',
        'DialogEnumValue_Character_FAILUREBOT': 'Failurebot',
        'DialogEnumValue_Character_FIELD_MARSHAL_KAZIAK': 'Kaziak',
        'DialogEnumValue_Character_FILM_BUFF': 'Buff',
        'DialogEnumValue_Character_FILM_WALLA': 'Unintelligible Chatter',
        'DialogEnumValue_Character_FINCH': 'Finch',
        'DialogEnumValue_Character_FRANCIS': 'Francis',
        'DialogEnumValue_Character_GAMBLIN_MAN_STAN': 'Gamblin\' Man Stan',
        'DialogEnumValue_Character_GARY': 'Gary',
        'DialogEnumValue_Character_GENERAL_MARKS': 'General Marks',
        'DialogEnumValue_Character_GENERAL_TRAUNT': 'General Traunt',
        'DialogEnumValue_Character_GENIVIV': 'GenIVIV',
        'DialogEnumValue_Character_GLENN': 'Glenn',
        'DialogEnumValue_Character_GOD_KINGS_CHOSEN': 'God-King\'s Chosen',
        'DialogEnumValue_Character_GOD_QUEENS_CHOSEN': 'God-Queen\'s Chosen',
        'DialogEnumValue_Character_GOLDEN_BULLION': 'Golden Bullion',
        'DialogEnumValue_Character_GOLIATH_1': 'Warden',
        'DialogEnumValue_Character_GOLIATH_RAGE_1': 'Raging Warden',
        'DialogEnumValue_Character_GOON_1': 'Hag',
        'DialogEnumValue_Character_GOREBOX': 'Gorebox',
        'DialogEnumValue_Character_GORE_GIRLS': 'Gore GIrls',
        'DialogEnumValue_Character_GRAND_ARCHIVIST': 'Grand Archivist',
        'DialogEnumValue_Character_GREEN_SKAG': 'Green Skag',
        'DialogEnumValue_Character_GROGMOUTH': 'Grogmouth',
        'DialogEnumValue_Character_GROG_KING': 'Grog King',
        'DialogEnumValue_Character_GROUSE': 'Grouse',
        'DialogEnumValue_Character_GUARDIAN_1': 'Grave',
        'DialogEnumValue_Character_GUARDIAN_2': 'Ward',
        'DialogEnumValue_Character_GUARDIAN_GUIDE': 'Guardian Guide',
        'DialogEnumValue_Character_HAMMERLOCK': 'Hammerlock',
        'DialogEnumValue_Character_HANDSOME_JACK': 'Handsome Jack',
        'DialogEnumValue_Character_HANDSOME_JACKIE': 'Handsome Jackie',
        'DialogEnumValue_Character_HARDIN': 'Hardin',
        'DialogEnumValue_Character_HARRIET': 'Harriet',
        'DialogEnumValue_Character_HEAVY_1': 'Lieutenant Preston',
        'DialogEnumValue_Character_HECKLE': 'Heckle',
        'DialogEnumValue_Character_HIRSCHIM': 'Hirschim',
        'DialogEnumValue_Character_HITCH': 'Hitch',
        'DialogEnumValue_Character_HIZZEN': 'Hizzen',
        'DialogEnumValue_Character_HOLDER': 'Holder',
        'DialogEnumValue_Character_HOLLOWAY': 'Holloway',
        'DialogEnumValue_Character_HOT_KARL': 'Hot Karl',
        'DialogEnumValue_Character_HYDE': 'Hyde',
        'DialogEnumValue_Character_JABBER_TRACKER': 'Rogue Tracker',
        'DialogEnumValue_Character_JAKOBS_LOYALIST_1': 'Kyle',
        'DialogEnumValue_Character_JAKOBS_LOYALIST_2': 'Jon Ryan',
        'DialogEnumValue_Character_JAKOBS_NARRATOR': 'Narrator',
        'DialogEnumValue_Character_JANICE_CARDALIA': 'Janice Cardalia',
        'DialogEnumValue_Character_JENSEN': 'Jensen',
        'DialogEnumValue_Character_JOY': 'Joy',
        'DialogEnumValue_Character_JUDGE_HIGHTOWER': 'Judge Hightower',
        'DialogEnumValue_Character_JUNO': 'Juno',
        'DialogEnumValue_Character_KATAGAWAJR': 'Katagawa Jr.',
        'DialogEnumValue_Character_KATAGAWA_BALL': 'Katagawa Ball',
        'DialogEnumValue_Character_KAY': 'Kay',
        'DialogEnumValue_Character_KIDNAPPER': 'Kidnapper',
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_1': 'Fangirl',
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_2': 'Fangirl',
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_3': 'Fangirl',
        'DialogEnumValue_Character_KILLAVOLT_FANGIRL_4': 'Fangirl',
        'DialogEnumValue_Character_KILLAVOLT_VIDEO': 'Killavolt',
        'DialogEnumValue_Character_KONRAD': 'Konrad',
        'DialogEnumValue_Character_KORMASH': 'Kormash',
        'DialogEnumValue_Character_KRIEG': 'Krieg',
        'DialogEnumValue_Character_KRIEG_PSYCHO': 'Psycho Krieg',
        'DialogEnumValue_Character_KRIEG_SANE': 'Sane Krieg',
        'DialogEnumValue_Character_KillaVolt': 'Killavolt',
        'DialogEnumValue_Character_LAGROMAR': 'Lagromar',
        'DialogEnumValue_Character_LANA': 'Lana Sh\'ani',
        'DialogEnumValue_Character_LARK': 'Lark',
        'DialogEnumValue_Character_LASER_TECHNICIAN': 'Laser Technician',
        'DialogEnumValue_Character_LASHLEY': 'Lashley',
        'DialogEnumValue_Character_LEAH_HART': 'Leah Hart',
        'DialogEnumValue_Character_LILITH': 'Lilith',
        'DialogEnumValue_Character_LIZZIE': 'Lizzie',
        'DialogEnumValue_Character_LOADER': 'Loader',
        'DialogEnumValue_Character_LOADER_1': 'Loader',
        'DialogEnumValue_Character_LORELEI': 'Lorelei',
        'DialogEnumValue_Character_LT_WELLS': 'Lt. Wells',
        'DialogEnumValue_Character_MALIWAN_PATROLMAN': 'Maliwan Patrolman',
        'DialogEnumValue_Character_MANCUBUS': 'Mancubus Bloodtooth',
        'DialogEnumValue_Character_MARCUS': 'Marcus',
        'DialogEnumValue_Character_MARK': 'Mark',
        'DialogEnumValue_Character_MAX_SKY': 'Max Sky',
        'DialogEnumValue_Character_MAYA': 'Maya',
        'DialogEnumValue_Character_MA_HONEYWELL': 'Ma Honeywell',
        'DialogEnumValue_Character_MECH_1': 'Hoplite',
        'DialogEnumValue_Character_MESSY_BREAKUP': 'Messy Breakup',
        'DialogEnumValue_Character_MICKEY_TRICKS': 'Mickey Tricks',
        'DialogEnumValue_Character_MILES': 'Prof. Miles Brown',
        'DialogEnumValue_Character_MILLER': 'Miller',
        'DialogEnumValue_Character_MILO_THE_MIME': 'Milo the Mime',
        'DialogEnumValue_Character_MONK_1': 'Athenas Monk',
        'DialogEnumValue_Character_MONTGOMERY_JAKOBS': 'Montgomery Jakobs',
        'DialogEnumValue_Character_MORDECAI': 'Mordecai',
        'DialogEnumValue_Character_MOUTHPIECE': 'Mouthpiece',
        'DialogEnumValue_Character_MOXXI_CROWD_MEDLEY': 'Unintelligible Chatter',
        'DialogEnumValue_Character_MURL': 'Murl',
        'DialogEnumValue_Character_Moxxi': 'Moxxi',
        'DialogEnumValue_Character_NAILS': 'Nails',
        'DialogEnumValue_Character_NAOKO': 'Naoko',
        'DialogEnumValue_Character_NEW-U': 'Sgt. Higgwink',
        'DialogEnumValue_Character_NEWS_ANCHOR': 'Shanneth Kyrie',
        'DialogEnumValue_Character_NILLY': 'Nilly',
        'DialogEnumValue_Character_NOG_1': 'NOG',
        'DialogEnumValue_Character_NPC_WALLA': 'Unintelligible Chatter',
        'DialogEnumValue_Character_NYRIAD': 'Nyriad',
        'DialogEnumValue_Character_OFFICER_TED': 'Officer Ted',
        'DialogEnumValue_Character_OFF_SCREEN_HOOLIGAN': 'Hooligan',
        'DialogEnumValue_Character_OLETTA': 'Oletta',
        'DialogEnumValue_Character_OVERSEER': 'Overseer',
        'DialogEnumValue_Character_OVERSPHERE': 'Oversphere',
        'DialogEnumValue_Character_PAIN': 'Pain',
        'DialogEnumValue_Character_PANDORA_FEMALE_1': 'Pandoran Civilian',
        'DialogEnumValue_Character_PANDORA_FEMALE_2': 'Pandoran Civilian',
        'DialogEnumValue_Character_PANDORA_MALE_1': 'Pandoran Civilian',
        'DialogEnumValue_Character_PANDORA_MALE_2': 'Pandoran Civilian',
        'DialogEnumValue_Character_PAPPY': 'Pappy',
        'DialogEnumValue_Character_PA_HONEYWELL': 'Pa Honeywell',
        'DialogEnumValue_Character_PIT_FIGHT_ANNOUNCER': 'Pit Fight Announcer',
        'DialogEnumValue_Character_PL_BEASTMASTER': 'FL4K',
        'DialogEnumValue_Character_PL_GUNNER': 'Moze',
        'DialogEnumValue_Character_PL_OPERATIVE': 'Zane',
        'DialogEnumValue_Character_PL_SIREN': 'Amara',
        'DialogEnumValue_Character_POLLI-BOT': 'Polli-Bot',
        'DialogEnumValue_Character_PORTAPOTTY_BANDIT': 'Trashmouth',
        'DialogEnumValue_Character_POWER_TROOPERS': 'Power Troopers',
        'DialogEnumValue_Character_PRETTY_BOY': 'Pretty Boy',
        'DialogEnumValue_Character_PRISA': 'Prisa',
        'DialogEnumValue_Character_PRISONER_WALLA': 'Unintelligible Chatter',
        'DialogEnumValue_Character_PROMETHEA_CIVILIAN_1': 'Promethean Civilian',
        'DialogEnumValue_Character_PROMETHEA_CIVILIAN_2': 'Promethean Civilian',
        'DialogEnumValue_Character_PROMETHEA_FEMALE_1': 'Promethean Civilian',
        'DialogEnumValue_Character_PROMETHEA_FEMALE_2': 'Promethean Civilian',
        'DialogEnumValue_Character_PROMETHEA_MALE_1': 'Promethean Civilian',
        'DialogEnumValue_Character_PROMETHEA_MALE_2': 'Promethean Civilian',
        'DialogEnumValue_Character_PSYCHO_FEMALE_1': 'Mommy Dearish',
        'DialogEnumValue_Character_PSYCHO_KILLER': 'Psycho Killer',
        'DialogEnumValue_Character_PSYCHO_MALE_1': 'Pinglover Psycho',
        'DialogEnumValue_Character_PUNK_FEMALE_1': 'Tumorhead',
        'DialogEnumValue_Character_PUNK_FEMALE_2': 'Sheega',
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_1': 'Audience Member',
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_2': 'Audience Member',
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_3': 'Audience Member',
        'DialogEnumValue_Character_PUNK_GAME_SHOW_CROWD_MEMBER_4': 'Audience Member',
        'DialogEnumValue_Character_PUNK_MALE_1': 'Rohner',
        'DialogEnumValue_Character_PUNK_MALE_2': 'Fanatic',
        'DialogEnumValue_Character_QUIETFOOT': 'Agent Quietfoot',
        'DialogEnumValue_Character_QUINN': 'Quinn',
        'DialogEnumValue_Character_RAKKMAN': 'I\'m Rakkman',
        'DialogEnumValue_Character_RAMSDEN': 'Ramsden',
        'DialogEnumValue_Character_RAZOR_TOOTH': 'Razor Tooth',
        'DialogEnumValue_Character_RECRUITMENT_BANDIT': 'Bandit Zealot',
        'DialogEnumValue_Character_RECRUITMENT_BANDIT_2': 'Bandit Zealot',
        'DialogEnumValue_Character_RED_JABBER': 'Red Jabber',
        'DialogEnumValue_Character_RED_SKAG': 'Red Skag',
        'DialogEnumValue_Character_RHYS': 'Rhys',
        'DialogEnumValue_Character_ROADDOG': 'Road Dog',
        'DialogEnumValue_Character_ROADDOG_RAGE': 'Raging Road Dog',
        'DialogEnumValue_Character_ROSE': 'Rose',
        'DialogEnumValue_Character_RUDY_VARLOPE': 'Rudy Varlope',
        'DialogEnumValue_Character_SALVADOR': 'Salvador',
        'DialogEnumValue_Character_SANDY_HART': 'Sandy Hart',
        'DialogEnumValue_Character_SARGEANT_BRIGS': 'Sgt. Brigs',
        'DialogEnumValue_Character_SATISFIED_CUSTOMER_1': 'Satisfied Customer 1',
        'DialogEnumValue_Character_SATISFIED_CUSTOMER_2': 'Satisfied Customer 2',
        'DialogEnumValue_Character_SATO': 'Sato',
        'DialogEnumValue_Character_SAURIAN_HIVEMIND': 'iOsaur, Queen of the Scaleon',
        'DialogEnumValue_Character_SAURIAN_QUEEN': 'iOsaur, Queen of the Scaleon',
        'DialogEnumValue_Character_SCRAPYARD_BANDIT_1': 'Bandit Zealot',
        'DialogEnumValue_Character_SCRUNTER': 'Scrunter',
        'DialogEnumValue_Character_SECURITYMADAM': 'Orbital Security',
        'DialogEnumValue_Character_SECURITY_TERMINAL': 'Security Terminal',
        'DialogEnumValue_Character_SERGEANT_HEADLEY': 'Sgt. Headly',
        'DialogEnumValue_Character_SERGEANT_HIGGWINK': 'Sgt. Higgwink',
        'DialogEnumValue_Character_SERGEANT_HOMINS': 'Sgt. Homins',
        'DialogEnumValue_Character_SERVICE_BOT': 'Service Bot',
        'DialogEnumValue_Character_SERVICE_BOT_FIRE_1': 'Fire Bot',
        'DialogEnumValue_Character_SERVICE_BOT_LAW_1': 'Johnny Law Bot',
        'DialogEnumValue_Character_SERVICE_BOT_MED_1': 'EMS BOT',
        'DialogEnumValue_Character_SERVICE_BOT_SWAT_1': 'Sheriff Bot',
        'DialogEnumValue_Character_SERVICE_BOT_WMS_1': 'Lark',
        'DialogEnumValue_Character_SHELLY': 'Shelly',
        'DialogEnumValue_Character_SHERIFF': 'Sheriff',
        'DialogEnumValue_Character_SHIV': 'Shiv',
        'DialogEnumValue_Character_SIBLINGS_WALLA': 'Unintelligible Chatter',
        'DialogEnumValue_Character_SKYLER': 'Skyman',
        'DialogEnumValue_Character_SLOTH': 'Sloth',
        'DialogEnumValue_Character_SMUGGLER_1': 'Smuggler 1',
        'DialogEnumValue_Character_SMUGGLER_2': 'Smuggler 2',
        'DialogEnumValue_Character_SOAPY_STEVE': 'Soapy Steve',
        'DialogEnumValue_Character_SOURBONES': 'Sour Bones',
        'DialogEnumValue_Character_SPARROW': 'Sparrow',
        'DialogEnumValue_Character_STANK_KNEE': 'Stank Knee',
        'DialogEnumValue_Character_STEEL_DRAGON': 'Steel Dragon of Eternal Pain',
        'DialogEnumValue_Character_STEPHIE': 'Stephie',
        'DialogEnumValue_Character_STEVE': 'Steve',
        'DialogEnumValue_Character_STICKLY': 'Stickly',
        'DialogEnumValue_Character_SUN_SMASHER_BANDIT': 'Bandit',
        'DialogEnumValue_Character_SUN_SMASHER_CLAN': 'Sun Smasher Clan Members',
        'DialogEnumValue_Character_SWARM_CLAPTRAP_1': 'Scraptrap',
        'DialogEnumValue_Character_SYLESTRO': 'Sylestro',
        'DialogEnumValue_Character_TALON': 'Talon',
        'DialogEnumValue_Character_TANNIS': 'Tannis',
        'DialogEnumValue_Character_TANYA': 'Tanya',
        'DialogEnumValue_Character_TEDIORE': 'Tediore',
        'DialogEnumValue_Character_TERN': 'Tern',
        'DialogEnumValue_Character_TERROR': 'Pain',
        'DialogEnumValue_Character_TERRY': 'Terry',
        'DialogEnumValue_Character_THE_UNSTOPPABLE': 'The Unstoppable?',
        'DialogEnumValue_Character_THE_UNSTOPPABLE_RAGE': 'The Unstoppable',
        'DialogEnumValue_Character_THIRD_RAIL': 'Third Rail',
        'DialogEnumValue_Character_THUNK': 'Thunk',
        'DialogEnumValue_Character_TIMOTHY': 'Timothy Lawrence',
        'DialogEnumValue_Character_TINA': 'Tina',
        'DialogEnumValue_Character_TINK_1': 'Interrogator',
        'DialogEnumValue_Character_TINK_LOOT_1': 'Under Taker',
        'DialogEnumValue_Character_TINK_PSYCHO_1': 'Psycho Tink',
        'DialogEnumValue_Character_TINK_TV': 'Tink',
        'DialogEnumValue_Character_TITUS': 'Titus',
        'DialogEnumValue_Character_TODD_BARLOS': 'Todd Barlos',
        'DialogEnumValue_Character_TONGUE_BANDIT': 'Tongue Bandit',
        'DialogEnumValue_Character_TONY': 'Tony Bordel',
        'DialogEnumValue_Character_TORGUE': 'Torgue',
        'DialogEnumValue_Character_TOWER_DEFENDER': 'Atlas Soldier',
        'DialogEnumValue_Character_TOWNSFOLK_FEMALE_3': 'Eudice',
        'DialogEnumValue_Character_TOWNSFOLK_MALE_2': 'Cato',
        'DialogEnumValue_Character_TRASHLANTIS_FEMALE_1': 'Trashlantis Citizen',
        'DialogEnumValue_Character_TRENT_THE_SLUT': 'Trent the Slut',
        'DialogEnumValue_Character_TROOPER_1': 'Assault Trooper',
        'DialogEnumValue_Character_TROOPER_2': 'Wired Will',
        'DialogEnumValue_Character_TROY_CALYPSO': 'Troy',
        'DialogEnumValue_Character_TUMORHEAD': 'Tumorhead',
        'DialogEnumValue_Character_TUNNEL_DWELLER': 'Tunnel Dweller',
        'DialogEnumValue_Character_TURNKEY_TIM_ENFORCER': 'Turnkey Tim',
        'DialogEnumValue_Character_TYPHON_DELEON': 'Typhon DeLeon',
        'DialogEnumValue_Character_TYREEN_CALYPSO': 'Tyreen',
        'DialogEnumValue_Character_VAUGHN': 'Vaughn',
        'DialogEnumValue_Character_VERCUVIO': 'Vercuvio',
        'DialogEnumValue_Character_VERONICA': 'VR-0N1CA',
        'DialogEnumValue_Character_VIC': 'Vic',
        'DialogEnumValue_Character_VICS_HEAD': 'Vic',
        'DialogEnumValue_Character_VIDEO_NARRATOR': 'Narrator',
        'DialogEnumValue_Character_VINCENT': 'Vincent',
        'DialogEnumValue_Character_VLADOF_NARRATOR': 'Narrator',
        'DialogEnumValue_Character_WAINWRIGHT': 'Wainwright Jakobs',
        'DialogEnumValue_Character_WALLA': 'Gamblers',
        'DialogEnumValue_Character_WALLOW': 'Wallow',
        'DialogEnumValue_Character_WANDERER': 'Wanderer',
        'DialogEnumValue_Character_WARDEN': 'Warden',
        'DialogEnumValue_Character_WARTY': 'Warty Prime',
        'DialogEnumValue_Character_WATCHER': 'Overseer',
        'DialogEnumValue_Character_WATERSHIP_MED_BOT': 'BALEX',
        'DialogEnumValue_Character_WEDDING_GUEST': 'Wedding Guest',
        'DialogEnumValue_Character_WICK': 'Wick',
        'DialogEnumValue_Character_WREN': 'Wren',
        'DialogEnumValue_Character_YOUNG_ROSE': 'Rose',
        'DialogEnumValue_Character_YVAN': 'Yvan',
        'DialogEnumValue_Character_ZAHNZI': 'Zahnzi Kall',
        'DialogEnumValue_Character_ZED': 'Zed',
        'DialogEnumValue_Character_ZER0': 'Zer0',
        'DialogEnumValue_Character_ZIFF': 'Ziff',
    }

    # Get results
    results = {}
    with open(json_path, encoding='utf-8') as df:
        data = json.load(df)
        for export in data:
            if export['export_type'] == 'DialogScriptData':
                # if export['Guid'] in guid_set:
                    guid = export['Guid']
                    results[guid] = []
                    try:
                        for time_idx, time in enumerate(export['TimeSlots']):
                            timeslotdata = data[time['export'] - 1]
                            for line_idx, line in enumerate(timeslotdata['Lines']):
                                linedata = data[line['export'] - 1]
                                try:
                                    speaker = linedata['SpeakingCharacter'][0]
                                    if speaker in DNTNames:
                                        speaker = ' / '.join('{}'.format(value) for value in DNTNames[speaker])
                                    else:  # Speaker name is not shown in-game?
                                        if speaker in DialogEnumValueNames:
                                            speaker = DialogEnumValueNames[speaker] + '*'
                                        else:
                                            # print(f'*** Speaker name for {speaker} is missing! ***')
                                            speaker = speaker.removeprefix('DialogEnumValue_Character_').replace('_', ' ').title() + '**'
                                except KeyError as e:
                                    print(f'*** {e.args[0]} key for GUID {linedata['Guid']} is missing! ***')
                                    speaker = '<missing>'
                                for perf_idx, perf in enumerate(linedata['Performances']):
                                    perfdata = data[perf['export'] - 1]
                                    try:
                                        textdata = perfdata['Text']
                                        try:
                                            text = textdata['string']
                                        except KeyError as e:
                                            print(f'*** {e.args[0]} key for GUID {perfdata['Guid']} is missing! ***')
                                            text = '<missing>'
                                        try:
                                            text_key = textdata['key']
                                        except KeyError as e:
                                            print(f'*** {e.args[0]} key for GUID {perfdata['Guid']} is missing! ***')
                                            text_key = '<missing>'
                                    except KeyError as e:
                                        print(f'*** {e.args[0]} key for GUID {perfdata['Guid']} is missing! ***')
                                        text = '<missing>'
                                        text_key = '<missing>'
                                    try:
                                        SoundFileName = perfdata['WwiseEventShortID']
                                    except KeyError as e:
                                        try:
                                            print(f'*** {e.args[0]} key for GUID {perfdata['Guid']} is missing! ***')
                                        except:
                                            print(f'*** {e.args[0]} key for Key {perfdata['Text']['key']} is missing! ***')
                                        SoundFileName = '<missing>'
                                    results[guid].append(f'{time_idx} | {line_idx} | {perf_idx} | {SoundFileName : >12} | {text_key} | {speaker}: {text}')
                    except KeyError as e:
                        print(f'*** {e.args[0]} key for GUID {guid} is missing! ***')

    # Report on results
    # for guid in args.guids:
        if guid in results:
            for line in results[guid]:
                print(line)
            print('')
        else:
            print(f'{guid} - Not found!')
            print('')


if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    main()
